47.Graceful Failure in the Transport Serializer Failing on Missing JSON Field
Let's add code to check for a different possible problem: let's check to see if this emoji key is missing: if not isset($data['emoji']), this time throw a normal exception: throw new \Exception('Missing the emoji key!').

Ok, move over and restart the worker:
php bin/console messenger:consume -vv external_messages

Back in Rabbit, remove the extra comma and change emoji to emojis. Publish! Over in the terminal... great! It exploded! And other than the exception class... it looks identical to the failure we saw before:

  Exception: Missing the emoji key!

But... something different did just happen. Try running the worker again:
php bin/console messenger:consume -vv external_messages
Woh! It exploded! Missing the emoji key. Run it again:
php bin/console messenger:consume -vv external_messages

The same error! This is the difference between throwing a normal Exception in the serializer versus the special MessageDecodingFailedException. When you throw a MessageDecodingFailedException, your serializer is basically saying:

  Hey! Something went wrong... and I do want to throw an exception. But, I think we should discard this message from the queue: there is no point to trying it over and over again. kthxbai!